services:
  basic-tv:
    build: .
    container_name: basic-tv
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - REGIONS=us,uk,ca
      - TIMEZONE=America/Chicago