services:
  basic-tv:
    build: .
    container_name: basic-tv
    ports:
      - "3000:3000" # host:container
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NUXT_EPG_URL=http://10.10.10.5:8182/epg.xml
      - NUXT_PLAYLIST_URL=http://10.10.10.5:8182/playlist.m3u8
    command: yarn start # Run Nuxt in production mode