version: '3'
services:
  nuxt-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - PLAYLIST_URL==http://10.10.10.5:34400/m3u/xteve.m3u
    command: yarn start # Run Nuxt in production mode